org.jwcarman.methodical.autoconfigure.GsonAutoConfiguration=
org.jwcarman.methodical.autoconfigure.GsonAutoConfiguration.AutoConfigureBefore=org.jwcarman.methodical.autoconfigure.MethodicalAutoConfiguration
org.jwcarman.methodical.autoconfigure.GsonAutoConfiguration.ConditionalOnBean=com.google.gson.Gson
org.jwcarman.methodical.autoconfigure.GsonAutoConfiguration.ConditionalOnClass=com.google.gson.Gson
org.jwcarman.methodical.autoconfigure.Jackson2AutoConfiguration=
org.jwcarman.methodical.autoconfigure.Jackson2AutoConfiguration.AutoConfigureBefore=org.jwcarman.methodical.autoconfigure.MethodicalAutoConfiguration
org.jwcarman.methodical.autoconfigure.Jackson2AutoConfiguration.ConditionalOnBean=com.fasterxml.jackson.databind.ObjectMapper
org.jwcarman.methodical.autoconfigure.Jackson2AutoConfiguration.ConditionalOnClass=com.fasterxml.jackson.databind.ObjectMapper
org.jwcarman.methodical.autoconfigure.Jackson3AutoConfiguration=
org.jwcarman.methodical.autoconfigure.Jackson3AutoConfiguration.AutoConfigureBefore=org.jwcarman.methodical.autoconfigure.MethodicalAutoConfiguration
org.jwcarman.methodical.autoconfigure.Jackson3AutoConfiguration.ConditionalOnBean=tools.jackson.databind.ObjectMapper
org.jwcarman.methodical.autoconfigure.Jackson3AutoConfiguration.ConditionalOnClass=tools.jackson.databind.ObjectMapper
org.jwcarman.methodical.autoconfigure.MethodicalAutoConfiguration=
